// Generated from the public Doka content repository.
// We keep only factual catalog metadata and generate original Front Gym Pro lessons from it.
// Source: https://github.com/doka-guide/content
// Counts: html: 136, css: 335, js: 244, a11y: 163, tools: 90, recipes: 44
export const dokaReferenceSeeds = [
  ["html", "a", "`<a>`"],
  ["html", "abbr", "`<abbr>`"],
  ["html", "accept", "Атрибут `accept`"],
  ["html", "address", "`<address>`"],
  ["html", "alt", "`alt`"],
  ["html", "area", "`<area>`"],
  ["html", "article", "`<article>`"],
  ["html", "aside", "`<aside>`"],
  ["html", "audio", "`<audio>`"],
  ["html", "autocomplete", "Атрибут `autocomplete`"],
  ["html", "autofocus", "Атрибут `autofocus`"],
  ["html", "b", "`<b>`"],
  ["html", "base", "`<base>`"],
  ["html", "bdi", "`<bdi>`"],
  ["html", "bdo", "`<bdo>`"],
  ["html", "blockquote", "`<blockquote>`"],
  ["html", "body", "`<body>`"],
  ["html", "br", "`<br>`"],
  ["html", "button", "`<button>`"],
  ["html", "canvas", "`<canvas>`"],
  ["html", "caption", "`<caption>`"],
  ["html", "capture", "Атрибут `capture`"],
  ["html", "cite", "`<cite>`"],
  ["html", "class", "Атрибут `class`"],
  ["html", "code", "`<code>`"],
  ["html", "col", "`<col>`"],
  ["html", "colgroup", "`<colgroup>`"],
  ["html", "comments", "Комментарии в HTML"],
  ["html", "crossorigin", "Атрибут `crossorigin`"],
  ["html", "d", "Атрибут `d`"],
  ["html", "data", "`<data>`"],
  ["html", "data-attributes", "Атрибуты `data-*`"],
  ["html", "datalist", "`<datalist>`"],
  ["html", "defer-async", "Атрибуты `defer` и `async`"],
  ["html", "del", "`<del>`"],
  ["html", "deprecated-tags", "Устаревшие теги"],
  ["html", "details", "`<details>`, `<summary>`"],
  ["html", "dfn", "`<dfn>`"],
  ["html", "dialog", "`<dialog>`"],
  ["html", "dir", "Атрибут `dir`"],
  ["html", "disabled", "Атрибут `disabled`"],
  ["html", "div", "`<div>`"],
  ["html", "dl-dd-dt", "`<dl>`, `<dd>`, `<dt>`"],
  ["html", "doctype", "`<!DOCTYPE>`"],
  ["html", "em", "`<em>`"],
  ["html", "embed", "`<embed>`"],
  ["html", "enterkeyhint", "Атрибут `enterkeyhint`"],
  ["html", "fieldset", "`<fieldset>`"],
  ["html", "figure-figcaption", "`<figure>`, `<figcaption>`"],
  ["html", "flow", "Поток документа"],
  ["html", "footer", "`<footer>`"],
  ["html", "for", "Атрибут `for`"],
  ["html", "form", "`<form>`"],
  ["html", "global-attrs", "Глобальные атрибуты"],
  ["html", "h1-h6", "`<h1>`...`<h6>`"],
  ["html", "head", "`<head>`"],
  ["html", "header", "`<header>`"],
  ["html", "hgroup", "`<hgroup>`"],
  ["html", "hidden", "Атрибут `hidden`"],
  ["html", "hr", "`<hr>`"],
  ["html", "html", "`<html>`"],
  ["html", "i", "`<i>`"],
  ["html", "iframe", "`<iframe>`"],
  ["html", "images-paste-methods", "Вставка изображений в HTML"],
  ["html", "img", "`<img>`"],
  ["html", "inert", "Атрибут `inert`"],
  ["html", "input", "`<input>`"],
  ["html", "inputmode", "Атрибут `inputmode`"],
  ["html", "ins", "`<ins>`"],
  ["html", "kbd", "`<kbd>`"],
  ["html", "label", "`<label>`"],
  ["html", "legend", "`<legend>`"],
  ["html", "li", "`<li>`"],
  ["html", "link", "`<link>`"],
  ["html", "main", "`<main>`"],
  ["html", "map", "`<map>`"],
  ["html", "mark", "`<mark>`"],
  ["html", "math", "`<math>`"],
  ["html", "menu", "`<menu>`"],
  ["html", "meta", "`<meta>`"],
  ["html", "meter", "`<meter>`"],
  ["html", "minlength-maxlength", "Атрибуты `minlength` и `maxlength`"],
  ["html", "multiple", "Атрибут `multiple`"],
  ["html", "nav", "`<nav>`"],
  ["html", "noindex", "`<noindex>`"],
  ["html", "noscript", "`<noscript>`"],
  ["html", "novalidate", "Атрибут `novalidate`"],
  ["html", "object", "`<object>`"],
  ["html", "ol", "`<ol>`"],
  ["html", "optgroup", "`<optgroup>`"],
  ["html", "option", "`<option>`"],
  ["html", "output", "`<output>`"],
  ["html", "p", "`<p>`"],
  ["html", "pattern", "Атрибут `pattern`"],
  ["html", "picture", "`<picture>`"],
  ["html", "placeholder", "Атрибут `placeholder`"],
  ["html", "popover", "Popover API"],
  ["html", "pre", "`<pre>`"],
  ["html", "progress", "`<progress>`"],
  ["html", "q", "`<q>`"],
  ["html", "readonly", "Атрибут `readonly`"],
  ["html", "rel", "Атрибут `rel`"],
  ["html", "required", "Атрибут `required`"],
  ["html", "ruby", "`<ruby>`"],
  ["html", "s", "`<s>`"],
  ["html", "samp", "`<samp>`"],
  ["html", "script", "`<script>`"],
  ["html", "search", "`<search>`"],
  ["html", "section", "`<section>`"],
  ["html", "select", "`<select>`"],
  ["html", "semantics", "Что такое семантика?"],
  ["html", "seo-for-beginners", "Поисковая оптимизация для начинающих"],
  ["html", "size", "Атрибут `size`"],
  ["html", "small", "`<small>`"],
  ["html", "source", "`<source>`"],
  ["html", "span", "`<span>`"],
  ["html", "step", "Атрибут `step`"],
  ["html", "strong", "`<strong>`"],
  ["html", "style", "`<style>`"],
  ["html", "sub", "`<sub>`"],
  ["html", "sup", "`<sup>`"],
  ["html", "svg", "`<svg>`"],
  ["html", "svg-sprite", "SVG-спрайт"],
  ["html", "tabindex", "Атрибут `tabindex`"],
  ["html", "tables", "Таблицы"],
  ["html", "template", "`<template>`"],
  ["html", "textarea", "`<textarea>`"],
  ["html", "time", "`<time>`"],
  ["html", "title", "`<title>`"],
  ["html", "track", "`<track>`"],
  ["html", "u", "`<u>`"],
  ["html", "ul", "`<ul>`"],
  ["html", "value", "Атрибут `value`"],
  ["html", "var", "`<var>`"],
  ["html", "video", "`<video>`"],
  ["html", "wbr", "`<wbr>`"],
  ["css", "accent-color", "`accent-color`"],
  ["css", "active", "`:active`"],
  ["css", "adding-styles", "Подключение стилей"],
  ["css", "after", "`::after`"],
  ["css", "align-content", "`align-content`"],
  ["css", "align-items", "`align-items`"],
  ["css", "align-self", "`align-self`"],
  ["css", "all", "`all`"],
  ["css", "anchor-function", "`anchor()`"],
  ["css", "anchor-name", "`anchor-name`"],
  ["css", "anchor-positioning-guide", "Гайд по Anchor Positioning"],
  ["css", "anchor-scope", "`anchor-scope`"],
  ["css", "anchor-size-function", "`anchor-size()`"],
  ["css", "animation", "CSS-анимации"],
  ["css", "animation-delay", "`animation-delay`"],
  ["css", "animation-direction", "`animation-direction`"],
  ["css", "animation-duration", "`animation-duration`"],
  ["css", "animation-fill-mode", "`animation-fill-mode`"],
  ["css", "animation-iteration-count", "`animation-iteration-count`"],
  ["css", "animation-name", "`animation-name`"],
  ["css", "animation-play-state", "`animation-play-state`"],
  ["css", "animation-timing-function", "`animation-timing-function`"],
  ["css", "appearance", "`appearance`"],
  ["css", "aspect-ratio", "`aspect-ratio`"],
  ["css", "attr", "`attr()`"],
  ["css", "attribute-selector", "Селектор по атрибуту"],
  ["css", "backdrop", "`::backdrop`"],
  ["css", "backdrop-filter", "`backdrop-filter`"],
  ["css", "backface-visibility", "`backface-visibility`"],
  ["css", "background", "`background`"],
  ["css", "background-attachment", "`background-attachment`"],
  ["css", "background-blend-mode", "`background-blend-mode`"],
  ["css", "background-clip", "`background-clip`"],
  ["css", "background-color", "`background-color`"],
  ["css", "background-image", "`background-image`"],
  ["css", "background-origin", "`background-origin`"],
  ["css", "background-position", "`background-position`"],
  ["css", "background-repeat", "`background-repeat`"],
  ["css", "background-size", "`background-size`"],
  ["css", "before", "`::before`"],
  ["css", "border", "`border`"],
  ["css", "border-block", "`border-block`"],
  ["css", "border-collapse", "`border-collapse`"],
  ["css", "border-color", "`border-color`"],
  ["css", "border-image", "`border-image`"],
  ["css", "border-inline", "`border-inline`"],
  ["css", "border-radius", "`border-radius`"],
  ["css", "border-spacing", "`border-spacing`"],
  ["css", "border-style", "`border-style`"],
  ["css", "border-width", "`border-width`"],
  ["css", "box-model", "Блочная модель"],
  ["css", "box-shadow", "`box-shadow`"],
  ["css", "box-sizing", "`box-sizing`"],
  ["css", "calc", "`calc()`"],
  ["css", "caption-side", "`caption-side`"],
  ["css", "caret-color", "`caret-color`"],
  ["css", "cascade", "Принцип каскада"],
  ["css", "charset", "`@charset`"],
  ["css", "checked", "`:checked`"],
  ["css", "child", "Псевдоклассы группы child"],
  ["css", "clamp", "`clamp()`"],
  ["css", "class-selector", "Селектор по классу"],
  ["css", "clip", "`clip`"],
  ["css", "clip-path", "`clip-path`"],
  ["css", "color", "`color`"],
  ["css", "color-function", "`color()`"],
  ["css", "color-mix", "`color-mix()`"],
  ["css", "color-scheme", "`color-scheme`"],
  ["css", "column-count", "`column-count`"],
  ["css", "column-fill", "`column-fill`"],
  ["css", "column-row-gap", "`row-gap`, `column-gap`"],
  ["css", "column-rule", "`column-rule`"],
  ["css", "column-rule-color", "`column-rule-color`"],
  ["css", "column-rule-style", "`column-rule-style`"],
  ["css", "column-rule-width", "`column-rule-width`"],
  ["css", "column-span", "`column-span`"],
  ["css", "column-width", "`column-width`"],
  ["css", "columns", "`columns`"],
  ["css", "combined-selectors", "Комбинированные селекторы"],
  ["css", "comments", "Комментарии в CSS"],
  ["css", "conic-gradient", "`conic-gradient()`"],
  ["css", "container", "`@container`"],
  ["css", "content", "`content`"],
  ["css", "counter-counters", "`counter()`, `counters()`"],
  ["css", "counter-increment", "`counter-increment`"],
  ["css", "counter-reset", "`counter-reset`"],
  ["css", "counter-set", "`counter-set`"],
  ["css", "counter-style", "`@counter-style`"],
  ["css", "css-counters", "Счётчики в CSS"],
  ["css", "css-rule", "CSS-правило"],
  ["css", "cue", "`::cue`"],
  ["css", "currentcolor", "`currentColor`"],
  ["css", "cursor", "`cursor`"],
  ["css", "custom-properties", "Кастомные свойства"],
  ["css", "default", "`:default`"],
  ["css", "details-content", "`::details-content`"],
  ["css", "disabled-enabled", "`:disabled`, `:enabled`"],
  ["css", "display", "`display`"],
  ["css", "empty", "`:empty`"],
  ["css", "env", "`env()`"],
  ["css", "file-selector-button", "`::file-selector-button`"],
  ["css", "fill", "`fill`"],
  ["css", "filter", "`filter`"],
  ["css", "filter-functions", "Функции фильтров"],
  ["css", "first-letter", "`::first-letter`"],
  ["css", "first-line", "`::first-line`"],
  ["css", "flex", "`flex`"],
  ["css", "flex-basis", "`flex-basis`"],
  ["css", "flex-direction", "`flex-direction`"],
  ["css", "flex-flow", "`flex-flow`"],
  ["css", "flex-grow", "`flex-grow`"],
  ["css", "flex-grow-shrink", "Как реально работают `flex-shrink` и `flex-grow`"],
  ["css", "flex-shrink", "`flex-shrink`"],
  ["css", "flex-wrap", "`flex-wrap`"],
  ["css", "flexbox-guide", "Гайд по flexbox"],
  ["css", "float", "`float`"],
  ["css", "focus", "`:focus`"],
  ["css", "focus-visible", "`:focus-visible`"],
  ["css", "focus-within", "`:focus-within`"],
  ["css", "font", "`font`"],
  ["css", "font-display", "`font-display`"],
  ["css", "font-face", "`@font-face`"],
  ["css", "font-family", "`font-family`"],
  ["css", "font-feature-settings", "`font-feature-settings`"],
  ["css", "font-feature-values", "`@font-feature-values`"],
  ["css", "font-kerning", "`font-kerning`"],
  ["css", "font-language-override", "`font-language-override`"],
  ["css", "font-optical-sizing", "`font-optical-sizing`"],
  ["css", "font-size", "`font-size`"],
  ["css", "font-size-adjust", "`font-size-adjust`"],
  ["css", "font-smooth", "`font-smooth`"],
  ["css", "font-stretch", "`font-stretch`"],
  ["css", "font-style", "`font-style`"],
  ["css", "font-synthesis", "`font-synthesis`"],
  ["css", "font-variant", "`font-variant`"],
  ["css", "font-variant-alternates", "`font-variant-alternates`"],
  ["css", "font-variant-caps", "`font-variant-caps`"],
  ["css", "font-variant-east-asian", "`font-variant-east-asian`"],
  ["css", "font-variant-ligatures", "`font-variant-ligatures`"],
  ["css", "font-variant-numeric", "`font-variant-numeric`"],
  ["css", "font-variant-position", "`font-variant-position`"],
  ["css", "font-variation-settings", "`font-variation-settings`"],
  ["css", "font-weight", "`font-weight`"],
  ["css", "fullscreen", "`:fullscreen`"],
  ["css", "gap", "`gap`"],
  ["css", "global-keywords", "Глобальные ключевые слова"],
  ["css", "grid", "`grid`"],
  ["css", "grid-area", "`grid-area`"],
  ["css", "grid-auto-columns-rows", "`grid-auto-columns`, `grid-auto-rows`"],
  ["css", "grid-auto-flow", "`grid-auto-flow`"],
  ["css", "grid-column-row", "`grid-column`, `grid-row`"],
  ["css", "grid-guide", "Гайд по grid"],
  ["css", "grid-start-end", "`grid-column-start`, `grid-column-end`, `grid-row-start`, `grid-row-end`"],
  ["css", "grid-template", "`grid-template`"],
  ["css", "grid-template-areas", "`grid-template-areas`"],
  ["css", "grid-template-columns", "`grid-template-columns`"],
  ["css", "grid-template-rows", "`grid-template-rows`"],
  ["css", "has", "`:has()`"],
  ["css", "height", "`height`"],
  ["css", "hover", "`:hover`"],
  ["css", "hyphens", "`hyphens`"],
  ["css", "id-selector", "Селектор по идентификатору"],
  ["css", "image-rendering", "`image-rendering`"],
  ["css", "image-set", "`image-set()`"],
  ["css", "import", "`@import`"],
  ["css", "important", "!important"],
  ["css", "in-range-out-of-range", "`:in-range`, `:out-of-range`"],
  ["css", "indeterminate", "`:indeterminate`"],
  ["css", "inheritance", "Наследование"],
  ["css", "inset", "`inset`"],
  ["css", "invalid-valid", "`:invalid`, `:valid`"],
  ["css", "is", "`:is()`"],
  ["css", "justify-content", "`justify-content`"],
  ["css", "justify-items", "`justify-items`"],
  ["css", "justify-self", "`justify-self`"],
  ["css", "keyframes", "`@keyframes`"],
  ["css", "lang", "`:lang()`"],
  ["css", "layer", "`@layer`"],
  ["css", "letter-spacing", "`letter-spacing`"],
  ["css", "light-dark", "`light-dark()`"],
  ["css", "line-height", "`line-height`"],
  ["css", "linear-gradient", "`linear-gradient()`"],
  ["css", "link", "`:link`"],
  ["css", "list-style", "`list-style`"],
  ["css", "list-style-image", "`list-style-image`"],
  ["css", "list-style-position", "`list-style-position`"],
  ["css", "list-style-type", "`list-style-type`"],
  ["css", "logical-properties", "Логические свойства CSS"],
  ["css", "margin", "`margin`"],
  ["css", "marker", "`::marker`"],
  ["css", "max", "`max()`"],
  ["css", "media", "`@media`"],
  ["css", "min", "`min()`"],
  ["css", "mix-blend-mode", "`mix-blend-mode`"],
  ["css", "mobile-first-vs-desktop-first", "Mobile-first vs Desktop-first"],
  ["css", "namespace", "`@namespace`"],
  ["css", "nesting-selector", "Селектор потомка"],
  ["css", "not", "`:not`"],
  ["css", "nth-of-type", "Псевдоклассы группы type"],
  ["css", "numeric-types", "Единицы измерения"],
  ["css", "object-fit", "`object-fit`"],
  ["css", "object-position", "`object-position`"],
  ["css", "object-view-box", "`object-view-box`"],
  ["css", "opacity", "`opacity`"],
  ["css", "optional", "`:optional`"],
  ["css", "order", "`order`"],
  ["css", "orphans", "`orphans`"],
  ["css", "outline", "`outline`"],
  ["css", "outline-color", "`outline-color`"],
  ["css", "outline-offset", "`outline-offset`"],
  ["css", "outline-style", "`outline-style`"],
  ["css", "outline-width", "`outline-width`"],
  ["css", "overflow", "`overflow`"],
  ["css", "overflow-wrap", "`overflow-wrap`"],
  ["css", "overscroll-behavior", "`overscroll-behavior`"],
  ["css", "padding", "`padding`"],
  ["css", "page", "`@page`"],
  ["css", "perspective", "`perspective`"],
  ["css", "perspective-origin", "`perspective-origin`"],
  ["css", "picture-in-picture", "`:picture-in-picture`"],
  ["css", "pixel-perfect", "Подход «Pixel Perfect»"],
  ["css", "place-content", "`place-content`"],
  ["css", "place-items", "`place-items`"],
  ["css", "place-self", "`place-self`"],
  ["css", "placeholder", "`::placeholder`"],
  ["css", "placeholder-shown", "`:placeholder-shown`"],
  ["css", "pointer-events", "`pointer-events`"],
  ["css", "position", "`position`"],
  ["css", "position-anchor", "`position-anchor`"],
  ["css", "position-area", "`position-area`"],
  ["css", "position-sticky", "`position: sticky`"],
  ["css", "position-try", "`position-try`"],
  ["css", "position-try-fallbacks", "`position-try-fallbacks`"],
  ["css", "position-try-order", "`position-try-order`"],
  ["css", "position-try-rule", "`@position-try`"],
  ["css", "position-visibility", "`position-visibility`"],
  ["css", "prefers-color-scheme", "`prefers-color-scheme`"],
  ["css", "print-color-adjust", "`print-color-adjust`"],
  ["css", "pseudo-private-custom-property", "Псевдоприватные кастомные свойства"],
  ["css", "pseudoclasses", "Псевдоклассы"],
  ["css", "pseudoelements", "Псевдоэлементы"],
  ["css", "quotes", "`quotes`"],
  ["css", "radial-gradient", "`radial-gradient()`"],
  ["css", "read-only", "`:read-only`"],
  ["css", "read-write", "`:read-write`"],
  ["css", "rem-em", "`rem`, `em`"],
  ["css", "repeating-conic-gradient", "`repeating-conic-gradient()`"],
  ["css", "repeating-linear-gradient", "`repeating-linear-gradient()`"],
  ["css", "repeating-radial-gradient", "`repeating-radial-gradient()`"],
  ["css", "required", "`:required`"],
  ["css", "resize", "`resize`"],
  ["css", "root", "`:root`"],
  ["css", "rotate", "`rotate`"],
  ["css", "scale-function", "`scale()`"],
  ["css", "scope", "`@scope`"],
  ["css", "scroll-behavior", "`scroll-behavior`"],
  ["css", "scroll-margin", "`scroll-margin`"],
  ["css", "scroll-padding", "`scroll-padding`"],
  ["css", "scroll-snap-align", "`scroll-snap-align`"],
  ["css", "scroll-snap-stop", "`scroll-snap-stop`"],
  ["css", "scroll-snap-type", "`scroll-snap-type`"],
  ["css", "scrollbar-color", "`scrollbar-color`"],
  ["css", "scrollbar-gutter", "`scrollbar-gutter`"],
  ["css", "scrollbar-width", "`scrollbar-width`"],
  ["css", "selection", "`::selection`"],
  ["css", "selector-list", "Перечисление селекторов"],
  ["css", "shape-function", "`shape()`"],
  ["css", "skew-function", "`skew()`"],
  ["css", "specificity", "Специфичность"],
  ["css", "stacking-context", "Контекст наложения"],
  ["css", "starting-style", "`@starting-style`"],
  ["css", "stroke", "`stroke`"],
  ["css", "supports", "`@supports`"],
  ["css", "sv-lv-dv", "`sv`, `lv`, `dv`"],
  ["css", "tab-size", "`tab-size`"],
  ["css", "tag-selector", "Селектор по тегу"],
  ["css", "target", "`:target`"],
  ["css", "target-text", "`::target-text`"],
  ["css", "text-align", "`text-align`"],
  ["css", "text-align-last", "`text-align-last`"],
  ["css", "text-box", "`text-box`"],
  ["css", "text-box-edge", "`text-box-edge`"],
  ["css", "text-box-trim", "`text-box-trim`"],
  ["css", "text-decoration", "`text-decoration`"],
  ["css", "text-decoration-color", "`text-decoration-color`"],
  ["css", "text-decoration-line", "`text-decoration-line`"],
  ["css", "text-decoration-skip-ink", "`text-decoration-skip-ink`"],
  ["css", "text-decoration-style", "`text-decoration-style`"],
  ["css", "text-decoration-thickness", "`text-decoration-thickness`"],
  ["css", "text-indent", "`text-indent`"],
  ["css", "text-justify", "`text-justify`"],
  ["css", "text-orientation", "`text-orientation`"],
  ["css", "text-overflow", "`text-overflow`"],
  ["css", "text-rendering", "`text-rendering`"],
  ["css", "text-shadow", "`text-shadow`"],
  ["css", "text-size-adjust", "`text-size-adjust`"],
  ["css", "text-transform", "`text-transform`"],
  ["css", "text-underline-offset", "`text-underline-offset`"],
  ["css", "text-underline-position", "`text-underline-position`"],
  ["css", "text-wrap", "`text-wrap`"],
  ["css", "top-left-right-bottom", "`top`, `left`, `right`, `bottom`"],
  ["css", "touch-action", "`touch-action`"],
  ["css", "transform", "`transform`"],
  ["css", "transform-box", "`transform-box`"],
  ["css", "transform-function", "Функции CSS-трансформации"],
  ["css", "transform-origin", "`transform-origin`"],
  ["css", "transform-style", "`transform-style`"],
  ["css", "transition", "`transition`"],
  ["css", "transition-delay", "`transition-delay`"],
  ["css", "transition-duration", "`transition-duration`"],
  ["css", "transition-property", "`transition-property`"],
  ["css", "transition-timing-function", "`transition-timing-function`"],
  ["css", "universal-selector", "Универсальный селектор"],
  ["css", "url", "`url()`"],
  ["css", "user-select", "`user-select`"],
  ["css", "user-valid-invalid", "`:user-valid` и `:user-invalid`"],
  ["css", "var", "`var()`"],
  ["css", "vendor-prefixes", "Вендорные префиксы"],
  ["css", "vertical-align", "`vertical-align`"],
  ["css", "view-transition", "@view-transition"],
  ["css", "visibility", "`visibility`"],
  ["css", "visited", "`:visited`"],
  ["css", "vw-vh", "`vw`, `vh`, `vmin`, `vmax`"],
  ["css", "web-colors", "Цвета в вебе"],
  ["css", "where", "`:where()`"],
  ["css", "white-space", "`white-space`"],
  ["css", "widows", "`widows`"],
  ["css", "width", "`width`"],
  ["css", "will-change", "`will-change`"],
  ["css", "word-break", "`word-break`"],
  ["css", "word-spacing", "`word-spacing`"],
  ["css", "word-wrap", "`word-wrap`"],
  ["css", "writing-mode", "`writing-mode`"],
  ["css", "z-index", "`z-index`"],
  ["css", "zoom", "`zoom`"],
  ["js", "abort-controller", "AbortController"],
  ["js", "alert", "`alert()`"],
  ["js", "array-at", "`.at()`"],
  ["js", "array-buffer", "`ArrayBuffer`"],
  ["js", "array-concat", "`.concat()`"],
  ["js", "array-copy-within", "`.copyWithin()`"],
  ["js", "array-entries", "`.entries()`"],
  ["js", "array-every", "`.every()`"],
  ["js", "array-fill", "`.fill()`"],
  ["js", "array-filter", "`.filter()`"],
  ["js", "array-find", "`.find()`"],
  ["js", "array-find-index", "`.findIndex()`"],
  ["js", "array-find-last", "`.findLast()`"],
  ["js", "array-find-last-index", "`.findLastIndex()`"],
  ["js", "array-flat", "`.flat()`"],
  ["js", "array-flatmap", "`.flatMap()`"],
  ["js", "array-foreach", "`.forEach()`"],
  ["js", "array-from", "`Array.from()`"],
  ["js", "array-isarray", "`Array.isArray()`"],
  ["js", "array-join", "`.join()`"],
  ["js", "array-keys", "`.keys()`"],
  ["js", "array-length", "`.length`"],
  ["js", "array-map", "`.map()`"],
  ["js", "array-of", "`Array.of()`"],
  ["js", "array-pop", "`.pop()`"],
  ["js", "array-push", "`.push()`"],
  ["js", "array-reduce", "`.reduce()`"],
  ["js", "array-reduce-right", "`.reduceRight()`"],
  ["js", "array-reverse", "`.reverse()`"],
  ["js", "array-shift", "`.shift()`"],
  ["js", "array-slice", "`.slice()`"],
  ["js", "array-some", "`.some()`"],
  ["js", "array-sort", "`.sort()`"],
  ["js", "array-splice", "`.splice()`"],
  ["js", "array-to-locale-string", "`.toLocaleString()`"],
  ["js", "array-to-reversed", "`.toReversed()`"],
  ["js", "array-to-spliced", "`.toSpliced()`"],
  ["js", "array-to-string", "`.toString()`"],
  ["js", "array-tosorted", "array-tosorted"],
  ["js", "array-unshift", "`.unshift()`"],
  ["js", "array-values", "`.values()`"],
  ["js", "array-with", "`.with()`"],
  ["js", "arrays", "Массив"],
  ["js", "arrow-function", "Стрелочные функции"],
  ["js", "async-await", "`async/await`"],
  ["js", "async-in-js", "Асинхронность в JavaScript"],
  ["js", "atomics", "`Atomics`"],
  ["js", "bigint", "Большое целое"],
  ["js", "bind-call-apply", "`bind()`, `call()` и `apply()`"],
  ["js", "bom", "Браузерное окружение, BOM"],
  ["js", "boolean", "Булев тип"],
  ["js", "clearinterval", "`clearInterval()`"],
  ["js", "cleartimeout", "`clearTimeout()`"],
  ["js", "closures", "Области видимости"],
  ["js", "collection-weakmap", "WeakMap"],
  ["js", "confirm", "`confirm()`"],
  ["js", "console", "`Console`"],
  ["js", "console-log", "`console.log()`"],
  ["js", "const", "`const`"],
  ["js", "cookie", "`.cookie`"],
  ["js", "css-style-declaration", "`CSSStyleDeclaration`"],
  ["js", "custom-event", "Объект пользовательского события `CustomEvent`"],
  ["js", "data-view", "`DataView`"],
  ["js", "date", "`Date`"],
  ["js", "deal-with-forms", "Работа с формами"],
  ["js", "debounce", "Debounce на примере формы поиска"],
  ["js", "descriptors", "Дескрипторы"],
  ["js", "destructuring-assignment", "Деструктуризация"],
  ["js", "dispatch-event", "`.dispatchEvent()`"],
  ["js", "document-design-mode", "`document.designMode`"],
  ["js", "dom", "DOM"],
  ["js", "element", "`Element`"],
  ["js", "element-addeventlistener", "`.addEventListener()`"],
  ["js", "element-blur", "`.blur()`"],
  ["js", "element-classlist", "`.classList`"],
  ["js", "element-click", "`click`"],
  ["js", "element-closest", "`.closest()`"],
  ["js", "element-dataset", "`.dataset`"],
  ["js", "element-focus", "`.focus()`"],
  ["js", "element-get-property-value", ".getPropertyValue()"],
  ["js", "element-getattribute", "`.getAttribute()`"],
  ["js", "element-hidden", "`.hidden`"],
  ["js", "element-innerhtml", "`.innerHTML`"],
  ["js", "element-innertext", "`.innerText`"],
  ["js", "element-keydown", "`keydown`"],
  ["js", "element-keyup", "`keyup`"],
  ["js", "element-mouseout", "`mouseout`"],
  ["js", "element-mouseover", "`mouseover`"],
  ["js", "element-outerhtml", "`.outerHTML`"],
  ["js", "element-positioning-js", "Позиционирование элементов с помощью JavaScript"],
  ["js", "element-removeeventlistener", "`.removeEventListener()`"],
  ["js", "element-removeproperty", "`.removeProperty()`"],
  ["js", "element-scroll", "`scroll`"],
  ["js", "element-scrollby", "`.scrollBy()`"],
  ["js", "element-scrollintoview", "`.scrollIntoView()`"],
  ["js", "element-scrollsnapchange", "`scrollsnapchange`"],
  ["js", "element-scrollsnapchanging", "`scrollsnapchanging`"],
  ["js", "element-scrollto", "`.scrollTo()`"],
  ["js", "element-set-property", "`.setProperty()`"],
  ["js", "element-style", "`.style`"],
  ["js", "element-textcontent", "`.textContent`"],
  ["js", "element-touch", "`touch`"],
  ["js", "element-wheel", "`wheel`"],
  ["js", "errors", "`Error` и стандартные ошибки"],
  ["js", "event", "Объект события `Event`"],
  ["js", "event-beforeunload", "`beforeunload`"],
  ["js", "event-blur", "`blur`"],
  ["js", "event-change", "`change`"],
  ["js", "event-dblclick", "`dblclick`"],
  ["js", "event-domcontentloaded", "`DOMContentLoaded`"],
  ["js", "event-focus", "`focus`"],
  ["js", "event-focusin", "`focusin`"],
  ["js", "event-input", "`input`"],
  ["js", "event-invalid", "`invalid`"],
  ["js", "event-load", "`load`"],
  ["js", "event-prevent-default", "`.preventDefault()`"],
  ["js", "event-reset", "`reset`"],
  ["js", "event-submit", "`submit`"],
  ["js", "event-unload", "`unload`"],
  ["js", "events", "Событийная модель"],
  ["js", "execution-order", "Порядок выполнения"],
  ["js", "expressions-vs-statements", "Выражения и инструкции"],
  ["js", "fetch", "`fetch()`"],
  ["js", "finalization-registry", "`FinalizationRegistry`"],
  ["js", "for", "`for`"],
  ["js", "for-in", "`for`...`in`"],
  ["js", "for-of", "`for`...`of`"],
  ["js", "form-data", "`FormData`"],
  ["js", "forms", "`.forms`"],
  ["js", "function", "Функция"],
  ["js", "function-arguments-object", "Объект `arguments`"],
  ["js", "function-as-datatype", "Функция как тип данных"],
  ["js", "function-context", "`this`: контекст выполнения функций"],
  ["js", "generators", "Генераторы и yield"],
  ["js", "geolocation-api", "Geolocation API"],
  ["js", "getelementbyid", "`.getElementById()`"],
  ["js", "getelementsbyclassname", "`.getElementsByClassName()`"],
  ["js", "getelementsbytagname", "`.getElementsByTagName()`"],
  ["js", "group-by", "`.groupBy()`"],
  ["js", "htmlcollection-and-nodelist", "`HTMLCollection` и `NodeList`"],
  ["js", "if-else", "`if`...`else`"],
  ["js", "includes", "`.includes()`"],
  ["js", "index-of", "`.indexOf()`"],
  ["js", "infinite-scroll", "Подгрузка контента при прокрутке"],
  ["js", "intersection-observer", "`Intersection Observer`"],
  ["js", "intl-datetimeformat", "`Intl.DateTimeFormat`"],
  ["js", "iterator", "Итератор"],
  ["js", "iterator-filter", "`Iterator.prototype.filter()`"],
  ["js", "iterator-map", "`Iterator.prototype.map()`"],
  ["js", "iterator-take", "`Iterator.prototype.take()`"],
  ["js", "iterator-to-array", "`Iterator.prototype.toArray()`"],
  ["js", "language-versions", "Версии языка, транспайлеры, бандлеры"],
  ["js", "last-index-of", "`.lastIndexOf()`"],
  ["js", "local-storage", "`localStorage`"],
  ["js", "logic-operators", "Логические операторы"],
  ["js", "loop", "Цикл"],
  ["js", "map", "`Map`"],
  ["js", "match-media", "`window.matchMedia`"],
  ["js", "math", "Объект `Math`"],
  ["js", "math-floor", "`Math.floor()`, `Math.round()`, `Math.ceil()` и `Math.trunc()`"],
  ["js", "math-random", "`Math.random()`"],
  ["js", "micro-and-macro-tasks", "Микро- и макрозадачи"],
  ["js", "modules", "Модули, `import`/`export`"],
  ["js", "null-primitive", "`null`"],
  ["js", "number", "Число"],
  ["js", "number-is-nan", "`Number.isNaN()`"],
  ["js", "number-isfinite", "`Number.isFinite()`"],
  ["js", "number-toexponential", "`.toExponential()`"],
  ["js", "number-tostring", "`.toString()`"],
  ["js", "number-wrapper", "Обёртка `Number`"],
  ["js", "object", "Объект"],
  ["js", "object-tostring", "`.toString()`"],
  ["js", "objects-objects-everywhere", "Почти всё в JavaScript — объект"],
  ["js", "parsefloat", "`parseFloat()`"],
  ["js", "parseint", "`parseInt()`"],
  ["js", "performance", "`performance`"],
  ["js", "promise", "`Promise`"],
  ["js", "promise-all", "`Promise.all()`"],
  ["js", "promise-allsettled", "`Promise.allSettled()`"],
  ["js", "promise-any", "`Promise.any()`"],
  ["js", "promise-catch", "`.catch()`"],
  ["js", "promise-finally", "`.finally()`"],
  ["js", "promise-race", "`Promise.race()`"],
  ["js", "promise-then", "`.then()`"],
  ["js", "promise-try", "`Promise.try()`"],
  ["js", "promise-with-resolvers", "`Promise.withResolvers()`"],
  ["js", "prompt", "`prompt()`"],
  ["js", "query-selector", "`.querySelector()`"],
  ["js", "query-selector-all", "`.querySelectorAll()`"],
  ["js", "queuemicrotask", "`queueMicrotask()`"],
  ["js", "recursion", "Рекурсия"],
  ["js", "ref-type-vs-value-type", "Хранение по ссылке и по значению"],
  ["js", "return", "`return`"],
  ["js", "session-storage", "`sessionStorage`"],
  ["js", "set", "`Set`"],
  ["js", "set-add", "`.add()`"],
  ["js", "set-clear", "`.clear()`"],
  ["js", "set-constructor", "Конструктор"],
  ["js", "set-delete", "`.delete()`"],
  ["js", "set-difference", "`.difference()`"],
  ["js", "set-entries", "`.entries()`"],
  ["js", "set-foreach", "`.forEach()`"],
  ["js", "set-has", "`.has()`"],
  ["js", "set-intersection", "`.intersection()`"],
  ["js", "set-is-disjoint-from", "`isDisjointFrom()`"],
  ["js", "set-is-subset-of", "`.isSubsetOf()`"],
  ["js", "set-is-superset-of", "`.isSupersetOf()`"],
  ["js", "set-keys", "`.keys()`"],
  ["js", "set-size", "`.size`"],
  ["js", "set-symmetric-difference", "`.symmetricDifference()`"],
  ["js", "set-union", "`.union()`"],
  ["js", "set-values", "`.values()`"],
  ["js", "setinterval", "`setInterval()`"],
  ["js", "settimeout", "`setTimeout()`"],
  ["js", "shallow-or-deep-clone", "Поверхностное и глубокое копирование"],
  ["js", "shared-array-buffer", "`SharedArrayBuffer`"],
  ["js", "spread", "Спред-синтаксис `...`"],
  ["js", "string", "Строка"],
  ["js", "string-length", "`.length`"],
  ["js", "string-trim", ".trim()"],
  ["js", "string-wrapper", "Обёртка `String`"],
  ["js", "switch", "`switch`"],
  ["js", "symbol", "Символ"],
  ["js", "template-strings", "Шаблонные строки"],
  ["js", "ternary-operator", "Тернарный оператор"],
  ["js", "throttle", "Throttle на примере изменения страницы при прокрутке"],
  ["js", "try-catch", "`try`...`catch`"],
  ["js", "typecasting", "Преобразование типов"],
  ["js", "typed-array", "`TypedArray`"],
  ["js", "undefined", "`undefined`"],
  ["js", "urlsearchparams", "`URLSearchParams`"],
  ["js", "use-strict", "`use strict`"],
  ["js", "var-let", "Переменные `const`, `let` и `var`"],
  ["js", "weak-ref", "`WeakRef`"],
  ["js", "weak-set", "`WeakSet`"],
  ["js", "web-workers", "Web Workers"],
  ["js", "websocket", "WebSocket"],
  ["js", "while", "`while`"],
  ["js", "window-close", "`window.close()`"],
  ["js", "window-history", "`window.history`"],
  ["js", "window-location", "`window.location`"],
  ["js", "window-navigator", "`window.navigator`"],
  ["js", "window-open", "window.open()"],
  ["js", "window-print", "`window.print()`"],
  ["a11y", "a11y-html", "Основы доступного HTML"],
  ["a11y", "a11y-tree", "Дерево доступности"],
  ["a11y", "abstract-roles", "Абстрактные ARIA-роли"],
  ["a11y", "accessible-forms", "Доступные формы"],
  ["a11y", "accessible-names-and-descs", "Доступное имя и описание"],
  ["a11y", "aria-activedescendant", "`aria-activedescendant`"],
  ["a11y", "aria-atomic", "`aria-atomic`"],
  ["a11y", "aria-attrs", "ARIA-атрибуты"],
  ["a11y", "aria-autocomplete", "`aria-autocomplete`"],
  ["a11y", "aria-braillelabel", "`aria-braillelabel`"],
  ["a11y", "aria-brailleroledescription", "`aria-brailleroledescription`"],
  ["a11y", "aria-busy", "`aria-busy`"],
  ["a11y", "aria-checked", "`aria-checked`"],
  ["a11y", "aria-colcount", "`aria-colcount`"],
  ["a11y", "aria-colindex", "`aria-colindex`"],
  ["a11y", "aria-colindextext", "`aria-colindextext`"],
  ["a11y", "aria-colspan", "`aria-colspan`"],
  ["a11y", "aria-controls", "`aria-controls`"],
  ["a11y", "aria-current", "`aria-current`"],
  ["a11y", "aria-describedby", "`aria-describedby`"],
  ["a11y", "aria-description", "`aria-description`"],
  ["a11y", "aria-details", "`aria-details`"],
  ["a11y", "aria-disabled", "`aria-disabled`"],
  ["a11y", "aria-errormessage", "`aria-errormessage`"],
  ["a11y", "aria-expanded", "`aria-expanded`"],
  ["a11y", "aria-flowto", "`aria-flowto`"],
  ["a11y", "aria-haspopup", "`aria-haspopup`"],
  ["a11y", "aria-hidden", "`aria-hidden`"],
  ["a11y", "aria-intro", "Введение в ARIA"],
  ["a11y", "aria-invalid", "`aria-invalid`"],
  ["a11y", "aria-keyshortcuts", "`aria-keyshortcuts`"],
  ["a11y", "aria-label", "`aria-label`"],
  ["a11y", "aria-labelledby", "`aria-labelledby`"],
  ["a11y", "aria-level", "`aria-level`"],
  ["a11y", "aria-live", "`aria-live`"],
  ["a11y", "aria-modal", "`aria-modal`"],
  ["a11y", "aria-multiline", "`aria-multiline`"],
  ["a11y", "aria-multiselectable", "`aria-multiselectable`"],
  ["a11y", "aria-orientation", "`aria-orientation`"],
  ["a11y", "aria-owns", "`aria-owns`"],
  ["a11y", "aria-placeholder", "`aria-placeholder`"],
  ["a11y", "aria-posinset", "`aria-posinset`"],
  ["a11y", "aria-pressed", "`aria-pressed`"],
  ["a11y", "aria-readonly", "`aria-readonly`"],
  ["a11y", "aria-relevant", "`aria-relevant`"],
  ["a11y", "aria-required", "`aria-required`"],
  ["a11y", "aria-roledescription", "`aria-roledescription`"],
  ["a11y", "aria-roles", "ARIA-роли"],
  ["a11y", "aria-rowcount", "`aria-rowcount`"],
  ["a11y", "aria-rowindex", "`aria-rowindex`"],
  ["a11y", "aria-rowindextext", "`aria-rowindextext`"],
  ["a11y", "aria-rowspan", "`aria-rowspan`"],
  ["a11y", "aria-selected", "`aria-selected`"],
  ["a11y", "aria-setsize", "`aria-setsize`"],
  ["a11y", "aria-sort", "`aria-sort`"],
  ["a11y", "aria-valuemax", "`aria-valuemax`"],
  ["a11y", "aria-valuemin", "`aria-valuemin`"],
  ["a11y", "aria-valuenow", "`aria-valuenow`"],
  ["a11y", "aria-valuetext", "`aria-valuetext`"],
  ["a11y", "chto-takoe-a11y", "Что такое доступность"],
  ["a11y", "color-contrast", "Контрастность цветов в интерфейсе"],
  ["a11y", "content-hidden", "Как скрыть содержимое от скринридеров"],
  ["a11y", "css-impact-on-a11y", "Влияние CSS на доступность"],
  ["a11y", "forced-colors", "`forced-colors`"],
  ["a11y", "how-to-describe-pictures", "Как описывать картинки"],
  ["a11y", "inverted-colors", "`inverted-colors`"],
  ["a11y", "live-region", "Что такое изменяющаяся область"],
  ["a11y", "overlays", "Оверлеи и отдельные версии сайтов"],
  ["a11y", "prefers-contrast", "`prefers-contrast`"],
  ["a11y", "prefers-reduced-motion", "`prefers-reduced-motion`"],
  ["a11y", "prefers-reduced-transparency", "`prefers-reduced-transparency`"],
  ["a11y", "role-alert", "`alert`"],
  ["a11y", "role-alertdialog", "`alertdialog`"],
  ["a11y", "role-application", "`application`"],
  ["a11y", "role-article", "`article`"],
  ["a11y", "role-associationlist", "`associationlist`"],
  ["a11y", "role-associationlistitemkey", "`associationlistitemkey`"],
  ["a11y", "role-associationlistitemvalue", "`associationlistitemvalue`"],
  ["a11y", "role-banner", "`banner`"],
  ["a11y", "role-blockquote", "`blockquote`"],
  ["a11y", "role-button", "`button`"],
  ["a11y", "role-caption", "`caption`"],
  ["a11y", "role-cell", "`cell`"],
  ["a11y", "role-checkbox", "`checkbox`"],
  ["a11y", "role-code", "`code`"],
  ["a11y", "role-columnheader", "`columnheader`"],
  ["a11y", "role-combobox", "`combobox`"],
  ["a11y", "role-comment", "`comment`"],
  ["a11y", "role-complementary", "`complementary`"],
  ["a11y", "role-contentinfo", "`contentinfo`"],
  ["a11y", "role-definition", "`definition`"],
  ["a11y", "role-deletion", "`deletion`"],
  ["a11y", "role-dialog", "`dialog`"],
  ["a11y", "role-document", "`document`"],
  ["a11y", "role-emphasis", "`emphasis`"],
  ["a11y", "role-feed", "`feed`"],
  ["a11y", "role-figure", "`figure`"],
  ["a11y", "role-form", "`form`"],
  ["a11y", "role-generic", "`generic`"],
  ["a11y", "role-grid", "`grid`"],
  ["a11y", "role-gridcell", "`gridcell`"],
  ["a11y", "role-group", "`group`"],
  ["a11y", "role-heading", "`heading`"],
  ["a11y", "role-img-image", "`img`, `image`"],
  ["a11y", "role-insertion", "`insertion`"],
  ["a11y", "role-link", "`link`"],
  ["a11y", "role-list", "`list`"],
  ["a11y", "role-listbox", "`listbox`"],
  ["a11y", "role-listitem", "`listitem`"],
  ["a11y", "role-log", "`log`"],
  ["a11y", "role-main", "`main`"],
  ["a11y", "role-mark", "`mark`"],
  ["a11y", "role-marquee", "`marquee`"],
  ["a11y", "role-math", "`math`"],
  ["a11y", "role-menu", "`menu`"],
  ["a11y", "role-menubar", "`menubar`"],
  ["a11y", "role-menuitem", "`menuitem`"],
  ["a11y", "role-menuitemcheckbox", "`menuitemcheckbox`"],
  ["a11y", "role-menuitemradio", "`menuitemradio`"],
  ["a11y", "role-meter", "`meter`"],
  ["a11y", "role-navigation", "`navigation`"],
  ["a11y", "role-note", "`note`"],
  ["a11y", "role-option", "`option`"],
  ["a11y", "role-paragraph", "`paragraph`"],
  ["a11y", "role-presentation-none", "`presentation`, `none`"],
  ["a11y", "role-progressbar", "`progressbar`"],
  ["a11y", "role-radio", "`radio`"],
  ["a11y", "role-radiogroup", "`radiogroup`"],
  ["a11y", "role-region", "`region`"],
  ["a11y", "role-row", "`row`"],
  ["a11y", "role-rowgroup", "`rowgroup`"],
  ["a11y", "role-rowheader", "`rowheader`"],
  ["a11y", "role-scrollbar", "`scrollbar`"],
  ["a11y", "role-search", "`search`"],
  ["a11y", "role-searchbox", "`searchbox`"],
  ["a11y", "role-separator", "`separator`"],
  ["a11y", "role-slider", "`slider`"],
  ["a11y", "role-spinbutton", "`spinbutton`"],
  ["a11y", "role-status", "`status`"],
  ["a11y", "role-strong", "`strong`"],
  ["a11y", "role-subscript", "`subscript`"],
  ["a11y", "role-suggestion", "`suggestion`"],
  ["a11y", "role-superscript", "`superscript`"],
  ["a11y", "role-switch", "`switch`"],
  ["a11y", "role-tab", "`tab`"],
  ["a11y", "role-table", "`table`"],
  ["a11y", "role-tablist", "`tablist`"],
  ["a11y", "role-tabpanel", "`tabpanel`"],
  ["a11y", "role-term", "`term`"],
  ["a11y", "role-textbox", "`textbox`"],
  ["a11y", "role-time", "`time`"],
  ["a11y", "role-timer", "`timer`"],
  ["a11y", "role-toolbar", "`toolbar`"],
  ["a11y", "role-tooltip", "`tooltip`"],
  ["a11y", "role-tree", "`tree`"],
  ["a11y", "role-treegrid", "`treegrid`"],
  ["a11y", "role-treeitem", "`treeitem`"],
  ["a11y", "screenreaders", "Скринридеры"],
  ["a11y", "site-language", "Язык сайта и содержимого"],
  ["a11y", "skip-link", "Skip link"],
  ["a11y", "speech-recognition", "Распознавание речи"],
  ["a11y", "wcag", "Что такое WCAG"],
  ["a11y", "wcag-conformance-levels", "Уровни доступности"],
  ["tools", "agile", "Методологии разработки и Agile"],
  ["tools", "algorithm-complexity", "Как анализировать алгоритмы?"],
  ["tools", "apache-web-server", "Веб-сервер Apache"],
  ["tools", "api", "Что такое API"],
  ["tools", "architecture-and-design-patterns", "Архитектура и паттерны проектирования"],
  ["tools", "architecture-data-flow", "Организация потоков данных"],
  ["tools", "architecture-mvc", "Архитектурный паттерн MVC"],
  ["tools", "browsers-storages", "Хранение данных в браузере"],
  ["tools", "bundlers", "Системы сборки"],
  ["tools", "ci-cd", "Что такое CI/CD"],
  ["tools", "clean-architecture", "Трёхслойная архитектура"],
  ["tools", "cli", "Интерфейс командной строки"],
  ["tools", "cls", "CLS (Cumulative Layout Shift)"],
  ["tools", "cms", "Что такое CMS?"],
  ["tools", "code-review", "Что такое код-ревью"],
  ["tools", "code-style", "Стиль написания кода в команде"],
  ["tools", "coordinates", "Координаты"],
  ["tools", "cors", "Что такое CORS"],
  ["tools", "css-in-js", "Обзор CSS-in-JS"],
  ["tools", "deno", "Что такое Deno"],
  ["tools", "design-patterns-behaviorial", "Поведенческие паттерны проектирования"],
  ["tools", "design-patterns-creational", "Порождающие паттерны проектирования"],
  ["tools", "design-patterns-structural", "Структурные паттерны проектирования"],
  ["tools", "docker", "Что такое Docker"],
  ["tools", "docker-compose", "Мультиконтейнерное приложение и Docker Compose"],
  ["tools", "docker-data-management", "Управление данными в Docker"],
  ["tools", "dockerfile", "Как устроен Dockerfile"],
  ["tools", "elasticsearch", "Основы работы с Elasticsearch"],
  ["tools", "encoding", "Шифрование"],
  ["tools", "fcp", "FCP (First Contentful Paint)"],
  ["tools", "file", "Файл и файловые системы"],
  ["tools", "fp", "Функциональное программирование"],
  ["tools", "gateway-bff", "Паттерны Gateway и Backend-for-Frontend"],
  ["tools", "git-cli", "Git CLI"],
  ["tools", "github-actions", "GitHub Actions"],
  ["tools", "gitlab-ci-cd", "GitLab CI/CD"],
  ["tools", "gulp", "Gulp и его использование"],
  ["tools", "how-the-browser-creates-pages", "Как браузер рисует страницы"],
  ["tools", "how-to-enter-to-vim", "Как войти в Vim"],
  ["tools", "how-to-measure-and-improve-core-web-vitals", "Как измерять и улучшать Core Web Vitals"],
  ["tools", "how-to-simplify-tests", "Как упростить тестирование"],
  ["tools", "how-to-test-and-why", "Как и зачем писать тесты"],
  ["tools", "http-protocol", "Протокол HTTP"],
  ["tools", "inp", "INP (Interaction to Next Paint)"],
  ["tools", "integration-and-system-testing", "Интеграционное и системное тестирование"],
  ["tools", "ipv6-for-webdevs", "Протокол IPv6"],
  ["tools", "json", "JSON"],
  ["tools", "lcp", "LCP (Largest Contentful Paint)"],
  ["tools", "markdown", "Язык разметки Markdown"],
  ["tools", "microservices", "Микросервисы"],
  ["tools", "multitasking-and-processes", "Многозадачность и процессы"],
  ["tools", "network", "Работа с сетью"],
  ["tools", "network-models", "Модели сетевого взаимодействия"],
  ["tools", "nginx-web-server", "Веб-сервер Nginx"],
  ["tools", "nodejs", "Что такое Node.js"],
  ["tools", "nodejs-tooling", "Node.js для создания инструментов разработки"],
  ["tools", "oop", "Объектно-ориентированное программирование"],
  ["tools", "package-managers", "Пакетные менеджеры"],
  ["tools", "pixel-density", "Плотность пикселей"],
  ["tools", "preprocessors", "CSS-препроцессоры"],
  ["tools", "process-management", "Управление процессами"],
  ["tools", "programming-paradigms", "Парадигмы программирования"],
  ["tools", "pwa", "Прогрессивные веб-приложения"],
  ["tools", "react-and-alternatives", "React и альтернативы"],
  ["tools", "reactivity", "Реактивность в программировании"],
  ["tools", "rollup", "`Rollup`"],
  ["tools", "site-readers", "Настройка сайта для поисковиков и скринридеров"],
  ["tools", "ssh", "Доступ по SSH"],
  ["tools", "ssl-certificates", "SSL-сертификаты"],
  ["tools", "static-analysis", "Статический анализ кода"],
  ["tools", "static-site-generators", "Статические генераторы сайтов"],
  ["tools", "static-types", "TypeScript и статическая типизация"],
  ["tools", "structure-data-in-js", "Структуры данных в JavaScript"],
  ["tools", "tcp-udp-protocols", "Протоколы TCP и UDP"],
  ["tools", "tdd", "Разработка через тестирование (TDD)"],
  ["tools", "technical-debt", "Что такое технический долг"],
  ["tools", "testing-and-fake-objects", "Фиктивные объекты и данные, моки, стабы"],
  ["tools", "testing-with-jest", "Пишем первые тесты"],
  ["tools", "trivial-memory-model", "Как устроена память"],
  ["tools", "ttfb", "TTFB (Time to First Byte)"],
  ["tools", "url", "URL"],
  ["tools", "version-control", "Системы управления версиями"],
  ["tools", "web-app-types", "Виды веб-приложений"],
  ["tools", "web-app-works", "Как работают веб-приложения"],
  ["tools", "web-security", "Безопасность веб-приложений и распространённые атаки"],
  ["tools", "web-server", "Веб-сервер"],
  ["tools", "webpack", "Что такое Webpack"],
  ["tools", "what-is-web-vitals", "Что такое Core Web Vitals"],
  ["tools", "xml", "XML"],
  ["tools", "yaml", "YAML"],
  ["recipes", "ajax-form", "Асинхронная отправка формы"],
  ["recipes", "array-filling", "Создание массива из большого количества повторяющихся элементов"],
  ["recipes", "center", "Блок по центру экрана"],
  ["recipes", "character-counter", "Счётчик символов в поле ввода"],
  ["recipes", "checkbox-radio-style", "Стилизация чекбоксов и радиокнопок"],
  ["recipes", "container", "Колонка с контентом по центру экрана"],
  ["recipes", "dragndrop-upload", "Драг-н-дроп для загрузки файлов"],
  ["recipes", "dropdown-animation", "Плавное раскрытие выпадающего меню"],
  ["recipes", "dropdown-menu", "Выпадающее меню"],
  ["recipes", "expressive-react-maze", "Выразительный React: интерактивность на клиенте"],
  ["recipes", "expressive-react-rectangle", "Выразительный React: простые компоненты на сервере"],
  ["recipes", "font-script", "Собственный конвертер шрифтов"],
  ["recipes", "git-rebase-onto", "Как ребейзить ветку и не думать ни о чём"],
  ["recipes", "github-2fa-setup", "Как настроить двухфакторную аутентификацию на GitHub"],
  ["recipes", "github-add-readme", "Как написать README на GitHub"],
  ["recipes", "github-add-ssh-access", "Как настроить доступ по SSH на GitHub"],
  ["recipes", "github-add-user-to-repo", "Как добавить пользователей в репозиторий на GitHub"],
  ["recipes", "github-choose-license", "Как выбрать лицензию на GitHub"],
  ["recipes", "github-clone-repo", "Как клонировать репозиторий на GitHub"],
  ["recipes", "github-contributes-heatmap", "GitHub-плитка коммитов за год"],
  ["recipes", "github-editing-files-in-browser", "Как редактировать файлы на GitHub"],
  ["recipes", "github-manage-pull-request", "Как работать в пулреквестах на GitHub"],
  ["recipes", "github-new-fork", "Как создать форк репозитория на GitHub"],
  ["recipes", "github-new-issue", "Как создать ишью на GitHub"],
  ["recipes", "github-new-organization", "Как создать организацию на GitHub"],
  ["recipes", "github-new-profile", "Как создать профиль на GitHub"],
  ["recipes", "github-new-pull-request", "Как сделать пулреквест на GitHub"],
  ["recipes", "github-new-repo", "Как создать репозиторий на GitHub"],
  ["recipes", "github-pages-static-site", "Как опубликовать сайт прямо на GitHub"],
  ["recipes", "github-search-in-issues", "Как найти ишью в репозитории на GitHub"],
  ["recipes", "input-range-style", "Кастомный кроссбраузерный ползунок диапазона"],
  ["recipes", "lazy-load-with-preview", "Ленивая загрузка картинок с цветным превью"],
  ["recipes", "lets-encrypt-nginx", "Установка сертификатов Let’s Encrypt"],
  ["recipes", "masonry", "Плиточная раскладка"],
  ["recipes", "multicolor-text", "Разноцветный текст"],
  ["recipes", "popup", "Попап"],
  ["recipes", "progress", "Загрузка файла с прогресс-баром"],
  ["recipes", "self-hosted-preview", "Как сделать превью проекта на собственном сервере"],
  ["recipes", "short-links", "Короткие ссылки на NJS"],
  ["recipes", "skeleton", "Скелетон"],
  ["recipes", "slider", "Слайдер"],
  ["recipes", "snow", "Снежинки"],
  ["recipes", "tooltip", "Тултип"],
  ["recipes", "validation", "Мгновенная валидация форм"],
] as const;
